### Site info:
title: 茶码鼓捣
tagline: 记录生活工作点滴
author: chinant
email: chinant@21cn.com
description: "一个程序员的博客" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Java , Python , and other "
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chinant.github.io" # the base hostname & protocol for your site
locale: cn


### Personal info and site tools info:
twitter_username: chinant
github_username:  chinant
disqus_shortname: chinant
favicon:     "/images/favicon.ico"
aboutme: Hi, This is my home. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: 茶码鼓捣
      href: http://chinant.github.io
      title: chinant's website

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
